title: 유정현
description: Web Developer
site_title: '유정현 - Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: zxc0509
blog_url: https://www.nagekar.com
email: abhishek@nagekar.com
keybase_username: zxc0509
twitter_username: zxc0509
reddit_username: zxc0509

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 